name: number_plate_bot
services:
  bot:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DEFAULT_LANG: ru
    restart: unless-stopped
    volumes:
      - ./bot:/app/bot
      - ./bot.log:/app/bot.log
